theme: jekyll-theme-cayman

# --- General options --- #
show_downloads: true

# Name of website
title: JavaCC

# Short description of your site
description: JavaCC is an open source compiler compiler
