theme: jekyll-theme-cayman

# --- General options --- #
show_downloads: true

# Name of website
title: JavaCC

# Short description of your site
description: JavaCC is an open source compiler compiler

github:
  zip_url: https://github.com/javacc/javacc/archive/7.0.4.zip
  tar_url: https://github.com/javacc/javacc/archive/7.0.4.tar.gz
